# inspired by https://github.com/Symplify/Symplify/blob/master/.github/workflows/code_checks.yaml
name: Run Binary File

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    run_phar:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4']

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   run: vendor/bin/monorepo-builder
